### PR TITLE
Dev 1.12.2

### PR DESCRIPTION
**Pull request by CreeperCristo**
> #532 made a Spanish translation for the add-on!
[es_ES.txt](https://github.com/BlesseNtumble/GalaxySpace/files/6745909/es_ES.txt)

### CODE REVIEW

**Comment by CaveJohnson376** [comment]
i think you've opened pull request from wrong repo/branch

**Comment by CaveJohnson376** [comment]
i'd suggest you to check this tutorial, just in case
https://yangsu.github.io/pull-request-tutorial/#:~:text=pull%2Drequest%2Ddemo-,Creating%20a%20Pull%20Request,the%20%22Head%20branch%22%20dropdown.

**Comment by CreeperCristo** [comment]
Oh, thanks!

**Comment by CaveJohnson376** [comment]
your translation file was added by Blesse now
https://github.com/BlesseNtumble/GalaxySpace/commit/34db37abe5e76941b7112f54415ec0a40c3e7a1f

**Pull request closed without merging**
